# Generated by Django 5.0.1 on 2024-03-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nontrmnparticipants",
            name="emailaddress",
        ),
        migrations.RemoveField(
            model_name="nontrmnparticipants",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="nontrmnparticipants",
            name="lastname",
        ),
    ]
