# Generated by Django 5.0.1 on 2024-03-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_remove_awardsubcategory_award_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name": "Branch", "verbose_name_plural": "Branches"},
        ),
    ]
