# Generated by Django 5.0.1 on 2024-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_totalcredits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=255)),
                ('weaponsubcategory', models.CharField(max_length=25)),
                ('verified', models.BinaryField()),
            ],
        ),
    ]
