# Generated by Django 5.0.1 on 2024-02-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('playmode', models.CharField(max_length=10)),
                ('turnsplayed', models.IntegerField()),
                ('flagged', models.BinaryField()),
                ('gameid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.game')),
            ],
        ),
    ]
