# Generated by Django 5.0.1 on 2024-02-13 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardname', models.CharField(max_length=25)),
                ('weaponcategory', models.CharField(max_length=25)),
                ('mincredits', models.IntegerField()),
                ('branchid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.branch')),
            ],
        ),
        migrations.CreateModel(
            name='AwardSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaponsubcategory', models.CharField(max_length=25)),
                ('awardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.award')),
            ],
        ),
        migrations.CreateModel(
            name='NonTRMNParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailaddress', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('sessionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.session')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateawarded', models.DateField()),
                ('awardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.award')),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.person')),
            ],
        ),
        migrations.CreateModel(
            name='SessionParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField()),
                ('credits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.person')),
                ('sessionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.session')),
            ],
        ),
    ]
