# Generated by Django 5.0.1 on 2024-02-16 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_award_active_award_createdon_award_modifiedon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaponname', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='totalcredits',
            name='weaponsubcategory',
        ),
        migrations.AddField(
            model_name='totalcredits',
            name='weapon',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='models.weapon'),
        ),
    ]
