# Generated by Django 5.0.1 on 2024-02-16 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_weapon_remove_totalcredits_weaponsubcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='branchid',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='awardsubcategory',
            old_name='awardid',
            new_name='award',
        ),
        migrations.RenameField(
            model_name='nontrmnparticipants',
            old_name='sessionid',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='gameid',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='sessionparticipants',
            old_name='personid',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='sessionparticipants',
            old_name='sessionid',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='award',
            name='weaponcategory',
        ),
        migrations.RemoveField(
            model_name='awardsubcategory',
            name='weaponsubcategory',
        ),
        migrations.RemoveField(
            model_name='game',
            name='weaponsubcategory',
        ),
        migrations.AddField(
            model_name='award',
            name='weapon',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='models.weapon'),
        ),
        migrations.AddField(
            model_name='awardsubcategory',
            name='weapon',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='models.weapon'),
        ),
        migrations.AddField(
            model_name='game',
            name='weapon',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='models.weapon'),
        ),
    ]
