# Generated by Django 5.0.1 on 2024-02-17 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_rename_branchid_award_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gamename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='weaponname',
            new_name='name',
        ),
    ]
