# Generated by Django 5.0.1 on 2024-02-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_rename_gamename_game_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(editable=False, max_length=25),
        ),
    ]
