# Generated by Django 5.0.1 on 2024-02-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_weapon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='memberid',
            field=models.CharField(max_length=10),
        ),
    ]
