# Generated by Django 5.0.1 on 2024-02-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_alter_person_memberid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='isSuperUser',
            field=models.BooleanField(default=False),
        ),
    ]
