# Generated by Django 5.0.1 on 2024-02-27 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_person_isstaff_person_issuperuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='isStaff',
        ),
        migrations.RemoveField(
            model_name='person',
            name='isSuperUser',
        ),
        migrations.CreateModel(
            name='PersonRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.role')),
            ],
        ),
    ]
