# Generated by Django 5.0.1 on 2024-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0015_rename_role_role_name_person_role_delete_personroles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="award",
            name="mincredits",
        ),
        migrations.AddField(
            model_name="totalcredits",
            name="expert",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="totalcredits",
            name="high_expert",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="totalcredits",
            name="marksman",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="totalcredits",
            name="sharpshooter",
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name="PeopleAwards",
        ),
    ]
