# Generated by Django 5.0.1 on 2024-03-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0016_remove_award_mincredits_totalcredits_expert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totalcredits",
            name="expert",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="totalcredits",
            name="high_expert",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="totalcredits",
            name="marksman",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="totalcredits",
            name="sharpshooter",
            field=models.DateField(blank=True, null=True),
        ),
    ]
