# Generated by Django 5.0.1 on 2024-03-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0017_alter_totalcredits_expert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="turnsplayed",
            field=models.IntegerField(default=0),
        ),
    ]
