# Generated by Django 5.0.1 on 2024-03-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0018_alter_session_turnsplayed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="turnsplayed",
            field=models.IntegerField(null=True),
        ),
    ]
