# Generated by Django 5.0.1 on 2024-03-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0020_alter_totalcredits_weapontotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="nontrmnparticipants",
            name="fullname",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
