# Generated by Django 5.0.1 on 2024-03-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0021_nontrmnparticipants_fullname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Member", "verbose_name_plural": "Members"},
        ),
        migrations.AlterModelOptions(
            name="session",
            options={
                "verbose_name": "Game Session",
                "verbose_name_plural": "Game Sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="sessionparticipants",
            options={
                "verbose_name": "Game Session Player",
                "verbose_name_plural": "Game Session Players",
            },
        ),
        migrations.AlterModelOptions(
            name="totalcredits",
            options={
                "verbose_name": "Total Credit Log",
                "verbose_name_plural": "Total Credit Logs",
            },
        ),
    ]
